---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "mongo"
  namespace: "default"
  labels:
    app: "mongo"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "mongo"
  template:
    metadata:
      labels:
        app: "mongo"
    spec:
      containers:
      - name: "mongo"
        image: "gcr.io/fiddler/mongo:latest"
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "mongo-hpa"
  namespace: "default"
  labels:
    app: "mongo"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "mongo"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "mongo-service"
  namespace: "default"
  labels:
    app: "mongo"
spec:
  ports:
  - protocol: "TCP"
    port: 27017
  selector:
    app: "mongo"
  type: "ClusterIP"
